<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="IT1606511" name="com_hackathon_test.HotelBooking" tests="1" failures="0" timestamp="31 Oct 2020 12:51:07 GMT" time="2.980" errors="1">
  <testcase name="TestScenarioThree" time="2.980" classname="com_hackathon_test.HotelBooking">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com_hackathon_base.baseUI.takeScreenShotOnFailure(baseUI.java:435)
at com_hackathon_base.baseUI.reportFail(baseUI.java:424)
at com_hackathon_base.baseUI.invokeBrowser(baseUI.java:101)
at com_hackathon_test.HotelBooking.TestScenarioThree(HotelBooking.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- TestScenarioThree -->
</testsuite> <!-- com_hackathon_test.HotelBooking -->
